CREATE TABLE `wc2026_model_projections` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`match_id` varchar(16) NOT NULL,
	`model_version` varchar(32) NOT NULL,
	`n_simulations` int NOT NULL DEFAULT 1000000,
	`home_team` varchar(64),
	`away_team` varchar(64),
	`home_lambda` double,
	`away_lambda` double,
	`home_win_prob` double,
	`draw_prob` double,
	`away_win_prob` double,
	`proj_home_score` double,
	`proj_away_score` double,
	`proj_total` double,
	`proj_spread` double,
	`over_0_5` double,
	`over_1_5` double,
	`over_2_5` double,
	`under_2_5` double,
	`over_3_5` double,
	`btts_prob` double,
	`model_home_ml` smallint,
	`model_draw_ml` smallint,
	`model_away_ml` smallint,
	`model_total` double,
	`over_odds` smallint,
	`under_odds` smallint,
	`model_spread` double,
	`model_spread_raw` double,
	`home_spread_odds` smallint,
	`away_spread_odds` smallint,
	`nv_home_prob` double,
	`nv_draw_prob` double,
	`nv_away_prob` double,
	`nv_dc_1x` double,
	`nv_dc_x2` double,
	`dc_1x_odds` smallint,
	`dc_x2_odds` smallint,
	`nv_no_draw_home` double,
	`nv_no_draw_away` double,
	`no_draw_home_odds` smallint,
	`no_draw_away_odds` smallint,
	`btts_yes_odds` smallint,
	`btts_no_odds` smallint,
	`model_total_raw` double,
	`home_edge` double,
	`draw_edge` double,
	`away_edge` double,
	`model_lean` varchar(8),
	`lean_prob` double,
	`top_scorelines` text,
	`modeled_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `wc2026_model_projections_id` PRIMARY KEY(`id`),
	CONSTRAINT `uq_mp_match` UNIQUE(`match_id`)
);
--> statement-breakpoint
ALTER TABLE `wc2026_model_projections` ADD CONSTRAINT `wc2026_model_projections_match_id_wc2026_matches_match_id_fk` FOREIGN KEY (`match_id`) REFERENCES `wc2026_matches`(`match_id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX `idx_mp_match` ON `wc2026_model_projections` (`match_id`);