CREATE TABLE `wc2026_espn_lineups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`matchId` varchar(32) NOT NULL,
	`teamId` varchar(16),
	`teamAbbrev` varchar(8) NOT NULL,
	`teamName` varchar(64),
	`teamLogo` text,
	`teamColor` varchar(8),
	`formation` varchar(16),
	`isHome` tinyint NOT NULL,
	`athleteId` varchar(32) NOT NULL,
	`name` varchar(128) NOT NULL,
	`nameShort` varchar(64),
	`jersey` varchar(4),
	`formationPlace` varchar(4),
	`role` enum('starter','substitute','unused') NOT NULL,
	`createdAt` bigint NOT NULL,
	CONSTRAINT `wc2026_espn_lineups_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_wc2026_espn_lineups_match_player` UNIQUE(`matchId`,`athleteId`)
);
--> statement-breakpoint
CREATE TABLE `wc2026_espn_match_stats` (
	`id` int AUTO_INCREMENT NOT NULL,
	`matchId` varchar(32) NOT NULL,
	`homeTeamAbbrev` varchar(8) NOT NULL,
	`awayTeamAbbrev` varchar(8) NOT NULL,
	`homeShotsOnGoal` int,
	`awayShotsOnGoal` int,
	`homeShots` int,
	`awayShots` int,
	`homeShotsBlocked` int,
	`awayShotsBlocked` int,
	`homeHitWoodwork` int,
	`awayHitWoodwork` int,
	`homeAttemptsInsideBox` int,
	`awayAttemptsInsideBox` int,
	`homeAttemptsOutsideBox` int,
	`awayAttemptsOutsideBox` int,
	`homeAccuratePasses` int,
	`awayAccuratePasses` int,
	`homePassAccuracyPct` varchar(8),
	`awayPassAccuracyPct` varchar(8),
	`homePasses` int,
	`awayPasses` int,
	`homeTotalBackZonePass` int,
	`awayTotalBackZonePass` int,
	`homeTotalForwardZonePass` int,
	`awayTotalForwardZonePass` int,
	`homeAccurateLongBalls` int,
	`awayAccurateLongBalls` int,
	`homeAccurateCrosses` int,
	`awayAccurateCrosses` int,
	`homeTotalThrows` int,
	`awayTotalThrows` int,
	`homePassTouchesInOppBox` int,
	`awayPassTouchesInOppBox` int,
	`homeBigChancesCreated` int,
	`awayBigChancesCreated` int,
	`homeBigChancesMissed` int,
	`awayBigChancesMissed` int,
	`homeThroughBalls` int,
	`awayThroughBalls` int,
	`homeAttkTouchesInOppBox` int,
	`awayAttkTouchesInOppBox` int,
	`homeFouledInFinalThird` int,
	`awayFouledInFinalThird` int,
	`homeCornersWon` int,
	`awayCornersWon` int,
	`homeXG` decimal(6,3),
	`awayXG` decimal(6,3),
	`homeXGOpenPlay` decimal(6,3),
	`awayXGOpenPlay` decimal(6,3),
	`homeXGSetPlay` decimal(6,3),
	`awayXGSetPlay` decimal(6,3),
	`homeXGOT` decimal(6,3),
	`awayXGOT` decimal(6,3),
	`homeGkSaves` int,
	`awayGkSaves` int,
	`homeGoalKicks` int,
	`awayGoalKicks` int,
	`homeShotsFaced` int,
	`awayShotsFaced` int,
	`homeTotalHighClaims` int,
	`awayTotalHighClaims` int,
	`homePenaltyKicksSaved` int,
	`awayPenaltyKicksSaved` int,
	`homeTackles` int,
	`awayTackles` int,
	`homeInterceptions` int,
	`awayInterceptions` int,
	`homeClearances` int,
	`awayClearances` int,
	`homeRecoveries` int,
	`awayRecoveries` int,
	`homeDuelsWon` int,
	`awayDuelsWon` int,
	`homeDuels` int,
	`awayDuels` int,
	`homeAerialsWon` int,
	`awayAerialsWon` int,
	`homeFoulsCommitted` int,
	`awayFoulsCommitted` int,
	`homeOffsides` int,
	`awayOffsides` int,
	`homeFoulYellowCards` int,
	`awayFoulYellowCards` int,
	`homeFoulRedCards` int,
	`awayFoulRedCards` int,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `wc2026_espn_match_stats_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_wc2026_match_stats_matchId` UNIQUE(`matchId`)
);
--> statement-breakpoint
CREATE INDEX `idx_wc2026_espn_lineups_matchId` ON `wc2026_espn_lineups` (`matchId`);--> statement-breakpoint
CREATE INDEX `idx_wc2026_espn_lineups_athleteId` ON `wc2026_espn_lineups` (`athleteId`);--> statement-breakpoint
CREATE INDEX `idx_wc2026_espn_lineups_team` ON `wc2026_espn_lineups` (`teamAbbrev`);--> statement-breakpoint
CREATE INDEX `idx_wc2026_espn_lineups_role` ON `wc2026_espn_lineups` (`role`);--> statement-breakpoint
CREATE INDEX `idx_wc2026_match_stats_homeTeam` ON `wc2026_espn_match_stats` (`homeTeamAbbrev`);--> statement-breakpoint
CREATE INDEX `idx_wc2026_match_stats_awayTeam` ON `wc2026_espn_match_stats` (`awayTeamAbbrev`);